runtime: python311
service: bqproxy
entrypoint: gunicorn -b :$PORT main:app

# change service account to one that ONLY has the BQ Job User Role. It does not need any other permissions

service_account: bq-proxy@isb-cgc-dev-1.iam.gserviceaccount.com

vpc_access_connector:
  name: projects/isb-cgc-dev-1/locations/us-central1/connectors/bq-proxy-connector

#change the project_id. Set credentials_file if running locally
env_variables:
    PROJECT_ID: "isb-cgc-dev-1"
    CREDENTIALS_FILE_NEEDED: "false"
    CREDENTIALS_FILE: ""
    QUERY_QUOTA_GB: "50"
    HAS_DAILY_QUOTA: "true"
    DAILY_QUOTA_GB: "500"    
    REDIS_HOST: "10.136.26.155"
    REDIS_PORT: "6379"
    USER_QUERY_OK: "false" 

